language: ruby
rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --deployment --without development production
before_install: gem update bundler --pre
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:schema:load --quiet
notifications:
  email:
    - ogataken@gmail.com
script: bundle exec rspec -fd
